spring:
  application:
    name: order
  cloud:
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json
#            virtual-host: /
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: test

  zipkin:
    base-url: http://192.168.24.129:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.24.129/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
    password: root1!
    username: root
  rabbitmq:
    host: 192.168.24.129
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.24.129
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#  instance:
#    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.openfeign: debug




server:
  port: 7005

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

env:
  test
