spring:
  application:
    name: order
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: test
#    stream
#      bindings:
#        myMessage:
#          group: order
#          content-type: application/json
#  zipkin:
#    base-url: http://zipkin:9411/
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.128/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
    password: root1!
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.openfeign: debug
env:
  test12
