spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root1!
    url: jdbc:mysql://192.168.188.128:3306/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.188.128
    port: 5672
    username: guest
    password: guest
